### ISSUE TITLE
Suppoprt for Preferences dialog

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/beers-law-lab#293]
Tasks:

(1) Enable the Preferences dialog

(2) Review public query parameters, and decide which ones should be settable in the Preferences dialog.

(3) Add controls to Preferences dialog, as identified in (2).

**Comment by pixelzoom** [comment]
Sim-specific query parameters (and their documentation) are found in [BLLQueryParameters.ts](https://github.com/phetsims/beers-law-lab/blob/master/js/common/BLLQueryParameters.ts).  The public query parameters are:

* showSolutionVolume
* showSoluteAmount
* concentrationMeterUnits
* beakerUnits
* cuvetteSnapInterval

I've enabled the Preferences dialog, and added basic controls for `showSolutionVolume` and `showSoluteAmount`. (The actual controls can be changed when https://github.com/phetsims/joist/issues/842 has been addressed.)

@arouinfar which query parameters do you think are appropriate to put in Preferences?  My recommendation is all of the above except `cuvetteSnapInterval`.

**Comment by arouinfar** [comment]
> @arouinfar which query parameters do you think are appropriate to put in Preferences?  My recommendation is all of the above except `cuvetteSnapInterval`.

I agree, let's include everything in the dialog except for `cuvetteSnapInterval`.

> The actual controls can be changed when https://github.com/phetsims/joist/issues/842 has been addressed.

I think there's now a preferences (toggle?) control, but the issue is still in progress. I'm fine with you doing whatever is quick and functional, but if you would prefer a mockup, please let me know.

**Comment by pixelzoom** [comment]
> I think there's now a preferences (toggle?) control, but the issue is still in progress. 

Indeed, it's still in progress. So I'm not going to use it just yet, and will stick with the existing checkboxes.  And the 2 new preferences to add are radio button groups.

The screenshot below shows the 4 preferences that correspond to the 4 query parameters.  This is usable for now, and we can modify/polish when more work has been done on common-code Preferences dialog. 

@arouinfar ready for review.  If this looks OK, just unassign yourself. We'll leave this issue open to decide whether preferences need to be revised/polished before publishing.

<img width="716" alt="screenshot_2012" src="https://user-images.githubusercontent.com/3046552/206100015-a0676238-cb13-4f1e-a8c0-a63fb972d85e.png">

**Comment by arouinfar** [comment]
@pixelzoom everything behaves in master (aside from #295) but I just realized that `showSolutionVolume` always displays the volume in liters. This looks a little strange when the beaker units are in mL. I see two options here:
1.  Add the unit to the checkbox label, e.g. Show solution volume (L). 
2.  Change the behavior of `showSolutionVolume` to adapt to the beaker units selection. (Reopen https://github.com/phetsims/beers-law-lab/issues/161 or open a new issue if we decide to do this.)

On the surface, option (2) seems nice, but would require shifting the beaker and associated elements to the right to make space. The volume readout already escapes the layoutBounds displayed with `dev`, but luckily remains in view when the browser window is sized to the default layoutBounds.

I am fine with (1), but also happy to defer to @pixelzoom's preference.

**Comment by pixelzoom** [comment]
We should definitely display the solution volume in the same units as the tick marks. 

@arouinfar how would you feel about moving the "solution volume indicator" to the right side of the beaker, like this:
<img width="706" alt="screenshot_2017" src="https://user-images.githubusercontent.com/3046552/206538450-f54e62bc-fd03-485b-9a6b-e1f460240cb9.png">

**Comment by pixelzoom** [comment]
In the above commit, I fixed the value and units to match the beaker ticks, and I relocated the solution volume indicator.  

@arouinfar ready for review. If you have a better idea about where to locate the solution volume indicator, let me know.

**Comment by pixelzoom** [comment]
@arouinfar also wondering whether we need to address the case where the indicator is on a dark solution. Note that we've punted on that for tick marks and labels too.  We could put a translucent background on tick labels, but I'm not sure how to address the tick marks.

<img width="635" alt="screenshot_2018" src="https://user-images.githubusercontent.com/3046552/206553487-03ab1c3a-d7cb-42be-9063-e6bd8e91cbfb.png">

**Comment by arouinfar** [comment]
Thanks @pixelzoom. I like the indicator at the right edge. Let's add the transparent background behind the volume reading and tick labels. The ticks themselves can stay as-is.

**Comment by pixelzoom** [comment]
@arouinfar I'm wondering about case shown below, where the indicator overlaps the bottom of the beaker when the solution volume is zero.  Perhaps it won't look so bad when there's a translucent background on the indicator value.

<img width="745" alt="screenshot_2030" src="https://user-images.githubusercontent.com/3046552/206761292-ddbc5219-d99b-4c69-88d3-0ef5bece6e08.png">
